alter table jam.SF_NORM_ALARM add ADM_STATUS_TIMEOUT_FLAG  VARCHAR2(10);

alter table jam.SF_NORM_ALARM add ADM_AUTO_DISREGARD_FLAG  VARCHAR2(10);

alter table jam.SF_NORM_ALARM add ADM_RECOMM_CREATED_DATE DATE;

alter table jam.SF_NORM_ALARM add ADM_STATUS_BACKUP  VARCHAR2(255);