alter table jam.SF_CONTROL_SYS add CATEGORY VARCHAR2(255);
alter table jam.SF_CONTROL_SYS add EQUIPMENT VARCHAR2(255);
alter table jam.SF_CONTROL_SYS add LOCATION VARCHAR2(255);
alter table jam.SF_CONTROL_SYS add IS_ACTIVE VARCHAR2(10);
alter table jam.SF_CONTROL_SYS add OME_NAME VARCHAR2(255);
alter table jam.SF_CONTROL_SYS add PROBLEM_TYPE VARCHAR2(4000);
alter table jam.SF_CONTROL_SYS add SERIAL_NUMBER VARCHAR2(255);
alter table jam.SF_CONTROL_SYS add TAG_ID VARCHAR2(255);