CREATE TABLE SF_WORK_ORDER
(
  SF_WORK_ORDER_ID   VARCHAR2(18)
 ,SF_ASSET_ID        VARCHAR2(18)
 ,SF_WORK_ORDER_NAME VARCHAR2(255)
 ,WORK_ORDER_NO      VARCHAR2(255)
 ,SERIAL_NUMBER      VARCHAR2(255)
 ,CATEGORY           VARCHAR2(255)
 ,EQUIPMENT          VARCHAR2(255)
 ,LOCATION           VARCHAR2(255)
 ,PROBLEM_TYPE       VARCHAR2(255)
 ,SEVERITY_LEVEL     VARCHAR2(255)
 ,SF_SERVICE_PROVIDER_ID  VARCHAR2(18)
 ,SF_WORK_ORDER_NAME VARCHAR2(255)
 ,CONTRACTOR_NAME    VARCHAR2(255)
 ,WO_DETAILS         VARCHAR2(4000)
 ,SENDING_ACTION     VARCHAR2(255)
 ,SENDING_FLAG       VARCHAR2(10)
 ,EMAIL_FLAG         VARCHAR2(10)
 ,IS_DISPATCHED      VARCHAR2(10)
 ,IS_PENDING         VARCHAR2(10)
 ,LAST_ACTION        VARCHAR2(255)
 ,LAST_COMMENTS      VARCHAR2(255)
 ,ORIGINAL_QUEUE     VARCHAR2(255)
 ,WO_TYPE            VARCHAR2(100)
 ,SF_SITE_ID         VARCHAR2(18)
 ,SF_ALARM_ID        VARCHAR2(18)
 ,EXT_WO_NO          VARCHAR2(255)
 ,EXT_WO_STATUS      VARCHAR2(255)
 ,EXT_WO_EXCEPTION   VARCHAR2(2000)
 ,EXT_WO_CREATED_ON  DATE
 ,OPERATIONAL_STATUS VARCHAR2(255)
 ,REQUESTED_BY       VARCHAR2(255)
 ,LOCATION_DETAIL    VARCHAR2(255)
 ,SITE_NAME          VARCHAR2(255)
 ,CALL_BACK_NUMBER   VARCHAR2(255)
 ,created_on 		       DATE
 ,created_by 		       VARCHAR2(50)
 ,modified_on              DATE
 ,modified_by              VARCHAR2(50)
)
PCTFREE 10
INITRANS 1
MAXTRANS 255
TABLESPACE SFRCD01
STORAGE(INITIAL 16M
        NEXT 8M
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        PCTINCREASE 0
        )
/

ALTER TABLE SF_WORK_ORDER ADD (
  PRIMARY KEY
  (SF_WORK_ORDER_ID)
  USING INDEX
    TABLESPACE SFRCX01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          16M
                NEXT             8M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE)
  
/

ALTER TABLE SF_WORK_ORDER ADD CONSTRAINT REF_SF_WORK_ORDER_FK1
    FOREIGN KEY (SF_SITE_ID)
    REFERENCES SF_SITE(SF_SITE_ID)
/

ALTER TABLE SF_WORK_ORDER ADD CONSTRAINT REF_SF_WORK_ORDER_FK2
    FOREIGN KEY (SF_ASSET_ID)
    REFERENCES SF_CONTROL_SYS(SF_CONTROL_SYS_ID)
/

ALTER TABLE SF_WORK_ORDER ADD CONSTRAINT REF_SF_WORK_ORDER_FK3
    FOREIGN KEY (SF_ASSET_ID)
    REFERENCES SF_CONTROL_SYS(SF_CONTROL_SYS_ID)
/

ALTER TABLE SF_WORK_ORDER ADD CONSTRAINT REF_SF_WORK_ORDER_FK3
    FOREIGN KEY (SF_SERVICE_PROVIDER_ID)
    REFERENCES SF_SERVICE_PROVIDER(SF_SERVICE_PROVIDER_ID)
/