alter table jam.SF_CUSTOMER add EXT_APP_PERMISSION VARCHAR2(10);
alter table jam.SF_CUSTOMER add EXT_APP_USER VARCHAR2(50);
alter table jam.SF_CUSTOMER add EXT_APP_PASSWORD VARCHAR2(50);
alter table jam.SF_CUSTOMER add EXT_APP_URL1 VARCHAR2(255);
alter table jam.SF_CUSTOMER add EXT_APP_URL2 VARCHAR2(255);