CREATE TABLE SF_ASSET_TEMP
(
  ID                 NUMBER(19)
 ,PID                NUMBER(19)
 ,SF_SITE_ID         VARCHAR2(18)
 ,SF_ASSET_ID        VARCHAR2(18)
 ,SF_ASSET_PID       VARCHAR2(18)
 ,SF_ASSET_NAME      VARCHAR2(255)
 ,CATEGORY           VARCHAR2(255)
 ,EQUIPMENT          VARCHAR2(255)
 ,LOCATION           VARCHAR2(255)
 ,PROBLEM_TYPE       VARCHAR2(255)
 ,DESCRIPTION        VARCHAR2(255)
 ,SEND_FLAG          VARCHAR2(10)
 ,START_DATE 		 DATE
 ,END_DATE 		     DATE
 ,created_on 		 DATE
 ,created_by 		 VARCHAR2(50)
 ,modified_on        DATE
 ,modified_by        VARCHAR2(50)
 ,SYNCH_MSG          VARCHAR2(3000)
)
PCTFREE 10
INITRANS 1
MAXTRANS 255
TABLESPACE SFRCD01
STORAGE(INITIAL 16M
        NEXT 8M
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        PCTINCREASE 0
        )
/

ALTER TABLE SF_ASSET_TEMP ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE SFRCX01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          16M
                NEXT             8M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);
  
/

ALTER TABLE SF_ASSET_TEMP ADD CONSTRAINT REF_SF_ASSET_TEMP_FK1
    FOREIGN KEY (SF_SITE_ID)
    REFERENCES SF_SITE(SF_SITE_ID)
/

CREATE SEQUENCE SF_ASSET_TEMP_SQ
  MINVALUE 1
  NOMAXVALUE
  START WITH 1
  INCREMENT BY 1
  NOCYCLE
  NOCACHE
;

/

CREATE OR REPLACE TRIGGER SF_ASSET_TEMP_TG
  BEFORE INSERT ON SF_ASSET_TEMP
  FOR EACH ROW
  DECLARE
    n_id NUMBER;
    seq_name VARCHAR2(50);
  BEGIN
    seq_name := 'SF_ASSET_TEMP_SQ' || '.NEXTVAL';
    EXECUTE IMMEDIATE 'SELECT ' || seq_name || ' FROM DUAL' INTO n_id;
    :new.ID := n_id;
  END;
/