alter table jam.SF_MESSAGE_CONFIG add SOURCE_EXCLUDE VARCHAR2(4000);
alter table jam.SF_MESSAGE_CONFIG add DESCRIPTION_EXCLUDE VARCHAR2(4000);

alter table jam.SF_MESSAGE_CONFIG add ADM_AD_SOURCE_INCLUDE VARCHAR2(4000);
alter table jam.SF_MESSAGE_CONFIG add ADM_AD_DESCRIPTION_INCLUDE VARCHAR2(4000);